### ISSUE TITLE
 Submission Error evaluating user policy: <class 'gym.error.UnregisteredEnv'>

### ISSUE THREAD

**Issue by 1800012973** [haosulab/ManiSkill-Submission-Example#1]
Hello, I tried several times to submit but always got ` Error evaluating user policy: <class 'gym.error.UnregisteredEnv'>` on the submission page. I guess the mistake is from 

    def __init__(self, env_name):
        super().__init__()
        self.env = gym.make(env_name)
in `user_solution.py`. 
I have put `mani_skill` and `mani_skill_learn `files at the root level, and I added `import mani_skill.env` at the start of `user_solution.py`, but it doesn't work. `gym `and `sapein `packages are in `environment.yml`.  It's OK to evaluate on my local server.
How can I solve it?

**Comment by tongzhoumu** [comment]
Hi @1800012973,

Did you include the source code of ManiSkill in your submission? If so, please remove it. We have an internal version of ManiSkill which contains the test environments.

**Comment by 1800012973** [comment]
> Hi @1800012973,
> 
> Did you include the source code of ManiSkill in your submission? If so, please remove it. We have an internal version of ManiSkill which contains the test environments.

Thanks, solved!
