### ISSUE TITLE
Error: Error importing user policy: <class 'ModuleNotFoundError'>

### ISSUE THREAD

**Issue by shen-hhao** [haosulab/ManiSkill-Submission-Example#2]
I met with this error after submission. 
Then I submitted ManiSkill-Learn baseline after moving environment.yml(ManiSkill-Submission-Example) and user_solution.py(in ManiSkill-Learn /submission example) to the root of zip file. But it was the same error.

**Comment by tongzhoumu** [comment]
What is your username? We can have a look at your submssion.

**Comment by shen-hhao** [comment]
The username is EPIC Lab

**Comment by lz1oceani** [comment]
The environment yaml is not valid. We cannot do pip install.
